(function(G,p){G.MVPYoutubeLoader=function(D){function H(a){p.ajax({url:a,dataType:"jsonp"}).done(function(b){k="https://www.googleapis.com/youtube/v3/playlistItems?part=contentDetails"+r+"&playlistId="+b.items[0].contentDetails.relatedPlaylists.uploads+"&fields=items(contentDetails(videoId)"+t+"),nextPageToken&maxResults="+l+"&key="+n;d="youtube_playlist";v(k)}).fail(function(b,c,f){console.log(b,c,f)})}function v(a){p.ajax({url:a,dataType:"jsonp"}).done(function(b){if(b.error&&b.error.message&&
-1<b.error.message.indexOf("Exceeded")&&-1<b.error.message.indexOf("quota")){if(1<z.length&&(A++,A<z.length)){n=z[A];var c=a.substr(0,a.indexOf("&key=")+5);b=a.substr(a.indexOf("&part="));k=c=c+n+b;v(c)}}else{var f,w=b.items.length;(g=b.nextPageToken)&&(g=k+"&pageToken="+g);for(f=0;f<w&&e.length!=m;f++){var q=b.items[f];if("youtube_playlist"==d||"youtube_single"==d||"youtube_single_list"==d||"youtube_channel"==d)q.status?"public"==q.status.privacyStatus&&e.push(E(q,d)):q.snippet&&"Private video"!=
q.snippet.title&&e.push(E(q,d))}if("youtube_single"==d||"youtube_single_list"==d)p(x).trigger("MVPYoutubeLoader.END_LOAD",{data:e,nextPageToken:g});else if(e.length<m)if(g){e.length+l>m&&(l=m-e.length,b=g.substr(0,k.indexOf("&maxResults=")+12),f=g.substr(k.indexOf("&key=")),g=b+l.toString()+f);if("youtube_playlist"==d||"youtube_channel"==d)c=g;v(c)}else-1<y.playlistItemContent.indexOf("duration")?(B=e.length,u=0,C()):p(x).trigger("MVPYoutubeLoader.END_LOAD",{data:e,nextPageToken:g});else-1<y.playlistItemContent.indexOf("duration")?
(B=e.length,u=0,C()):p(x).trigger("MVPYoutubeLoader.END_LOAD",{data:e,nextPageToken:g})}}).fail(function(b,c,f){console.log(b,c,f)})}function C(){var a="",b,c=0;for(b=u;b<B&&(a+=e[b].path+",",c++,50!=c);b++);a=a.substr(0,a.length-1);p.ajax({url:"https://www.googleapis.com/youtube/v3/videos?id="+a+"&key="+n+"&part=contentDetails&fields=items(contentDetails(duration))",dataType:"jsonp"}).done(function(f){f.items.length!=c&&console.log("getYtDuration response length mismatch!");var w=f.items.length;
for(b=0;b<w;b++)e[u].duration=F(f.items[b].contentDetails.duration),u++;u<B?C():p(x).trigger("MVPYoutubeLoader.END_LOAD",{data:e,nextPageToken:g})}).fail(function(f,w,q){console.log(f,w,q)})}function E(a,b){var c=jQuery.extend(!0,{},h);c.type="youtube";"youtube_single"==b||"youtube_single_list"==b?c.path=a.id:"youtube_playlist"==b?c.path=a.contentDetails.videoId:"youtube_channel"==b&&(c.path=a.id.videoId);a.snippet&&(!c.title&&a.snippet.title&&(c.title=a.snippet.title),!c.description&&a.snippet.description&&
(c.description=a.snippet.description),a.snippet.publishedAt&&(c.date=a.snippet.publishedAt),!c.thumb&&a.snippet.thumbnails&&(c.thumbnails=a.snippet.thumbnails),a.snippet.liveBroadcastContent&&"live"==a.snippet.liveBroadcastContent&&(c.liveStream=!0));a.contentDetails&&(a.contentDetails.projection&&"360"==a.contentDetails.projection&&(c.is360=!0),!c.duration&&a.contentDetails.duration&&(c.duration=F(a.contentDetails.duration)));return c}function F(a){var b=a.match(/\d+/g);0<=a.indexOf("M")&&-1==a.indexOf("H")&&
-1==a.indexOf("S")&&(b=[0,b[0],0]);0<=a.indexOf("H")&&-1==a.indexOf("M")&&(b=[b[0],0,b[1]]);0<=a.indexOf("H")&&-1==a.indexOf("M")&&-1==a.indexOf("S")&&(b=[b[0],0,0]);a=0;3==b.length&&(a+=3600*parseInt(b[0]),a+=60*parseInt(b[1]),a+=parseInt(b[2]));2==b.length&&(a+=60*parseInt(b[0]),a+=parseInt(b[1]));1==b.length&&(a+=parseInt(b[0]));return a}var x=this,y=D,d,h,e=[],B,u,l=50,k,g,m,z=D.youtubeAppId.split(",").map(function(a){return a.trim()}),A=0,n=z[A],r,t;this.resumeLoad=function(a){e=[];a?(k=a.substr(0,
a.lastIndexOf("&pageToken=")),v(a)):p(x).trigger("MVPYoutubeLoader.END_LOAD",{data:e,nextPageToken:a})};this.setDataFromCache=function(a){e=[];h=a;m=h.limit||400;l=50;m<l&&(l=m);d=h.type};this.setData=function(a){if(n){e=[];h=a;m=h.limit||400;l=50;m<l&&(l=m);d=h.type;g=null;a="title,description,";if("youtube_single"==d||"youtube_single_list"==d)a+="liveBroadcastContent,";-1<y.playlistItemContent.indexOf("date")&&(a+="publishedAt,");-1<y.playlistItemContent.indexOf("thumb")&&(a+="thumbnails(default(url),standard(url),medium(url),high(url),maxres(url)),");
0<a.length?(a=a.substr(0,a.length-1),r=",snippet",t=",snippet("+a+")"):t=r="";if("youtube_single"==d||"youtube_single_list"==d)"youtube_single_list"==d&&(h.path=h.path.replace(/\s+/g,"")),k=-1<y.playlistItemContent.indexOf("duration")?"https://www.googleapis.com/youtube/v3/videos?id="+h.path+"&key="+n+"&part=id"+r+",contentDetails&fields=items(id"+t+",contentDetails(duration))":"https://www.googleapis.com/youtube/v3/videos?id="+h.path+"&key="+n+"&part=id"+r+"&fields=items(id"+t+")";else if("youtube_playlist"==
d)k="https://www.googleapis.com/youtube/v3/playlistItems?playlistId="+h.path+"&maxResults="+l+"&key="+n+"&part=contentDetails"+r+"&fields=items(contentDetails(videoId)"+t+"),nextPageToken";else{"youtube_channel"==d?(k="https://www.googleapis.com/youtube/v3/channels?part=contentDetails&id="+h.path+"&fields=items(contentDetails%2FrelatedPlaylists%2Fuploads)&key="+n,H(k)):console.log("Wrong youtube type!");return}v(k)}else alert("Youtube API key missing! Set Youtube API key in settings.")};this.getNextPageToken=
function(){return g}}})(window,jQuery);